--Subset Processing 

--Remove Existing metadata
DELETE [dbo].[CopyActivityExecutionPlan]
  FROM [dbo].[CopyActivityExecutionPlan] p
  JOIN CopyActivityExecutionGroup g on p.CopyActivityExecutionGroupKey = g.CopyActivityExecutionGroupKey
  Where g.CopyActivityExecutionGroupName = 'AX Subset Copy Process'

DELETE NotebookExecutionPlan
FROM NotebookExecutionPlan p
JOIN Notebook n ON p.NotebookKey = n.NotebookKey
JOIN Container c ON p.ContainerKey = c.ContainerKey
JOIN NotebookExecutionGroup g on p.NotebookExecutionGroupKey = g.NotebookExecutionGroupKey
WHERE g.NotebookExecutionGroupName like 'AX Subset%'


--Copy Activity for Tables used in the final Query
EXECUTE [dbo].[uspInsertSQLScriptCopyMetadata] @ContainerName = 'brtl',@CopyActivityExecutionGroupName = 'AX Subset Copy Process',@CopyActivityDataName='AX_PURCHLINEHISTORY',@CopyActivityParameterValue='AXConnectionString',@CopyActivityDataSQLScript='SELECT PURCHID
      ,ITEMID
      ,PURCHSTATUS
      ,SHIPPINGDATEREQUESTED
      ,DELIVERYDATE
      ,NAME
      ,TAXGROUP
      ,QTYORDERED
      ,PURCHRECEIVEDNOW
      ,REMAINPURCHPHYSICAL
      ,REMAINPURCHFINANCIAL
      ,PRICEUNIT
      ,PURCHPRICE
      ,CURRENCYCODE
      ,LINEPERCENT
      ,LINEDISC
      ,LINEAMOUNT
      ,EXTERNALITEMID
      ,PURCHUNIT
      ,CONFIRMEDDLV
      ,ADDRESSREFRECID
      ,INVENTTRANSID
      ,VENDGROUP
      ,VENDACCOUNT
      ,ADDRESSREFTABLEID
      ,PURCHQTY
      ,PURCHMARKUP
      ,INVENTRECEIVEDNOW
      ,MULTILNDISC
      ,MULTILNPERCENT
      ,PURCHASETYPE
      ,COVREF
      ,REMAININVENTPHYSICAL
      ,TAXITEMGROUP
      ,TRANSACTIONCODE
      ,SHIPPINGDATECONFIRMED
      ,COUNTYORIGDEST
      ,TAXAUTOGENERATED
      ,UNDERDELIVERYPCT
      ,OVERDELIVERYPCT
      ,TAX1099AMOUNT
      ,BARCODE
      ,BARCODETYPE
      ,INVENTREFID
      ,INVENTREFTRANSID
      ,ITEMREFTYPE
      ,PROJTRANSID
      ,BLOCKED
      ,COMPLETE
      ,REQPLANIDSCHED
      ,REQPOID
      ,ITEMROUTEID
      ,ITEMBOMID
      ,LINEHEADER
      ,SCRAP
      ,RETURNACTIONID
      ,INTERCOMPANYORIGIN
      ,PROJCATEGORYID
      ,PROJID
      ,INVENTDIMID
      ,TRANSPORT
      ,STATPROCID
      ,PORT
      ,ASSETID
      ,ASSETTRANSTYPEPURCH
      ,ASSETBOOKID
      ,PROJLINEPROPERTYID
      ,PROJTAXITEMGROUPID
      ,PROJTAXGROUPID
      ,PROJSALESPRICE
      ,PROJSALESCURRENCYID
      ,INTERCOMPANYINVENTTRANSID
      ,PROJSALESUNITID
      ,DELIVERYNAME
      ,DELIVERYTYPE
      ,CUSTOMERREF
      ,CUSTPURCHASEORDERFORMNUM
      ,STATTRIANGULARDEAL
      ,TAX1099STATE
      ,TAX1099STATEAMOUNT
      ,ITEMTAGGING
      ,CASETAGGING
      ,PALLETTAGGING
      ,REMAININVENTFINANCIAL
      ,PURCHREQLINEREFID
      ,DEPRECIATIONSTARTDATE
      ,ACTIVITYNUMBER
      ,RETURNSTATUS
      ,RETURNDISPOSITIONCODEID
      ,CREATEFIXEDASSET
      ,ASSETGROUP
      ,REQATTENTION
      ,PURCHREQID
      ,MATCHINGPOLICY
      ,PROCUREMENTCATEGORY
      ,LINEDELIVERYTYPE
      ,SOURCEDOCUMENTLINE
      ,DEFAULTDIMENSION
      ,LEDGERDIMENSION
      ,ITEMPBAID
      ,VALIDFROM
      ,VALIDFROMTZID
      ,VALIDTO
      ,VALIDTOTZID
      ,DISCPERCENT
      ,DISCAMOUNT
      ,CONFIRMEDTAXAMOUNT
      ,CONFIRMEDTAXWRITECODE
      ,MATCHINGAGREEMENTLINE
      ,TAX1099FIELDS
      ,ACCOUNTINGDISTRIBUTIONTEMPLATE
      ,DELIVERYPOSTALADDRESS
      ,LINENUMBER
      ,GSTHSTTAXTYPE_CA
      ,TAXWITHHOLDITEMGROUPHEADING_TH
      ,TAXWITHHOLDGROUP_TH
      ,TAXWITHHOLDBASECUR_TH
      ,REQUESTER
      ,STOCKEDPRODUCT
      ,ISFINALIZED
      ,TAX1099RECID
      ,AGREEMENTSKIPAUTOLINK
      ,CFOPTABLE_BR
      ,MCRDROPSHIPMENT
      ,MCRDROPSHIPCOMMENT
      ,MCRDROPSHIPSTATUS
      ,PDSCWINVENTRECEIVEDNOW
      ,PDSCWQTY
      ,PDSCWREMAININVENTFINANCIAL
      ,PDSCWREMAININVENTPHYSICAL
      ,PROJWORKER
      ,PURCHCOMMITMENTLINE_PSN
      ,TAXSERVICECODE_BR
      ,BUDGETRESERVATIONLINE_PSN
      ,DATAAREAID
      ,RECVERSION
      ,PARTITION
      ,RECID
  FROM dbo.PURCHLINEHISTORY WITH (NOLOCK)',@CopyActivityDataIncrementalSQLScript= 'SELECT PURCHID
      ,ITEMID
      ,PURCHSTATUS
      ,SHIPPINGDATEREQUESTED
      ,DELIVERYDATE
      ,NAME
      ,TAXGROUP
      ,QTYORDERED
      ,PURCHRECEIVEDNOW
      ,REMAINPURCHPHYSICAL
      ,REMAINPURCHFINANCIAL
      ,PRICEUNIT
      ,PURCHPRICE
      ,CURRENCYCODE
      ,LINEPERCENT
      ,LINEDISC
      ,LINEAMOUNT
      ,EXTERNALITEMID
      ,PURCHUNIT
      ,CONFIRMEDDLV
      ,ADDRESSREFRECID
      ,INVENTTRANSID
      ,VENDGROUP
      ,VENDACCOUNT
      ,ADDRESSREFTABLEID
      ,PURCHQTY
      ,PURCHMARKUP
      ,INVENTRECEIVEDNOW
      ,MULTILNDISC
      ,MULTILNPERCENT
      ,PURCHASETYPE
      ,COVREF
      ,REMAININVENTPHYSICAL
      ,TAXITEMGROUP
      ,TRANSACTIONCODE
      ,SHIPPINGDATECONFIRMED
      ,COUNTYORIGDEST
      ,TAXAUTOGENERATED
      ,UNDERDELIVERYPCT
      ,OVERDELIVERYPCT
      ,TAX1099AMOUNT
      ,BARCODE
      ,BARCODETYPE
      ,INVENTREFID
      ,INVENTREFTRANSID
      ,ITEMREFTYPE
      ,PROJTRANSID
      ,BLOCKED
      ,COMPLETE
      ,REQPLANIDSCHED
      ,REQPOID
      ,ITEMROUTEID
      ,ITEMBOMID
      ,LINEHEADER
      ,SCRAP
      ,RETURNACTIONID
      ,INTERCOMPANYORIGIN
      ,PROJCATEGORYID
      ,PROJID
      ,INVENTDIMID
      ,TRANSPORT
      ,STATPROCID
      ,PORT
      ,ASSETID
      ,ASSETTRANSTYPEPURCH
      ,ASSETBOOKID
      ,PROJLINEPROPERTYID
      ,PROJTAXITEMGROUPID
      ,PROJTAXGROUPID
      ,PROJSALESPRICE
      ,PROJSALESCURRENCYID
      ,INTERCOMPANYINVENTTRANSID
      ,PROJSALESUNITID
      ,DELIVERYNAME
      ,DELIVERYTYPE
      ,CUSTOMERREF
      ,CUSTPURCHASEORDERFORMNUM
      ,STATTRIANGULARDEAL
      ,TAX1099STATE
      ,TAX1099STATEAMOUNT
      ,ITEMTAGGING
      ,CASETAGGING
      ,PALLETTAGGING
      ,REMAININVENTFINANCIAL
      ,PURCHREQLINEREFID
      ,DEPRECIATIONSTARTDATE
      ,ACTIVITYNUMBER
      ,RETURNSTATUS
      ,RETURNDISPOSITIONCODEID
      ,CREATEFIXEDASSET
      ,ASSETGROUP
      ,REQATTENTION
      ,PURCHREQID
      ,MATCHINGPOLICY
      ,PROCUREMENTCATEGORY
      ,LINEDELIVERYTYPE
      ,SOURCEDOCUMENTLINE
      ,DEFAULTDIMENSION
      ,LEDGERDIMENSION
      ,ITEMPBAID
      ,VALIDFROM
      ,VALIDFROMTZID
      ,VALIDTO
      ,VALIDTOTZID
      ,DISCPERCENT
      ,DISCAMOUNT
      ,CONFIRMEDTAXAMOUNT
      ,CONFIRMEDTAXWRITECODE
      ,MATCHINGAGREEMENTLINE
      ,TAX1099FIELDS
      ,ACCOUNTINGDISTRIBUTIONTEMPLATE
      ,DELIVERYPOSTALADDRESS
      ,LINENUMBER
      ,GSTHSTTAXTYPE_CA
      ,TAXWITHHOLDITEMGROUPHEADING_TH
      ,TAXWITHHOLDGROUP_TH
      ,TAXWITHHOLDBASECUR_TH
      ,REQUESTER
      ,STOCKEDPRODUCT
      ,ISFINALIZED
      ,TAX1099RECID
      ,AGREEMENTSKIPAUTOLINK
      ,CFOPTABLE_BR
      ,MCRDROPSHIPMENT
      ,MCRDROPSHIPCOMMENT
      ,MCRDROPSHIPSTATUS
      ,PDSCWINVENTRECEIVEDNOW
      ,PDSCWQTY
      ,PDSCWREMAININVENTFINANCIAL
      ,PDSCWREMAININVENTPHYSICAL
      ,PROJWORKER
      ,PURCHCOMMITMENTLINE_PSN
      ,TAXSERVICECODE_BR
      ,BUDGETRESERVATIONLINE_PSN
      ,DATAAREAID
      ,RECVERSION
      ,PARTITION
      ,RECID
  FROM dbo.PURCHLINEHISTORY WITH (NOLOCK)
  WHERE Cast(DELIVERYDATE as Date)  >= Cast(DATEADD(DD,@IncrementalDays,GETDATE()) as Date)',@IsIncremental=1,@CopyActivityDataADLSFolderPath = '/Raw/AX/PURCHLINEHISTORY',@CopyActivityDataADLSFileName ='PURCHLINEHISTORY.json'

--Ingest data from raw zone (Json in adls) to query zone / current state (delta lake in adls)
EXECUTE [dbo].[uspInsertNotebookMetadata] @NotebookZone = 'Ingest', @ContainerExecutionGroupName = 'AX Subset' ,@ContainerName = 'brtl' ,@DataFactoryName = 'TBD' ,@NotebookName =   'AX_PURCHLINEHISTORY'  ,@NotebookOrder = '10'  ,@NumPartitions = '16' ,@QueryZoneSchemaName = 'brtl' ,@QueryZoneTableName = 'PURCHLINEHISTORY' ,@ExternalDataPath = '' ,@RawDataPath = '/Raw/AX/PURCHLINEHISTORY' ,@QueryZoneNotebookPath='/Framework/Query Zone Processing - Overwrite Delta Lake',@PrimaryKeyColumns = '';

-- Enrich to create symantic layer table to push to query zone / enrich and Synapse
EXECUTE [dbo].[uspInsertNotebookMetadata] @NotebookZone = 'Enrich', @ContainerExecutionGroupName = 'AX Subset' ,@ContainerName = 'brtl' ,@DataFactoryName = 'TBD' ,@NotebookName = 'AX_PURCHLINEHISTORY'  ,@NotebookOrder = '10'  ,@NumPartitions = '8' ,@QueryZoneSchemaName = 'brtl' ,@QueryZoneTableName = 'PURCHLINEHISTORY' ,@ExternalDataPath = '' ,@RawDataPath = '' ,@QueryZoneNotebookPath = '/Framework/Query Zone Processing - Enrich',@PrimaryKeyColumns = '' ,@TimeStampColumns = '';

-- Sanction push to synapse for standard notebooks (as is )
EXECUTE [dbo].[uspInsertNotebookMetadata] @NotebookZone = 'Sanction', @ContainerExecutionGroupName = 'AX Subset' ,@ContainerName = 'brtl' ,@DataFactoryName = 'TBD' ,@NotebookName = 'AX_PURCHLINEHISTORY'  ,@NotebookOrder = '10'  ,@NumPartitions = '8' ,@QueryZoneSchemaName = 'brtl' ,@QueryZoneTableName = 'PURCHLINEHISTORY' ,@ExternalDataPath = '' ,@RawDataPath = '' ,@SanctionedZoneNotebookPath = '/Framework/Sanctioned Zone Processing - Load Synapse DW',@PrimaryKeyColumns = '' ,@TimeStampColumns = '';


	